name: Bandit Security Analysis

on:
  push:
    paths:
      - '**/*.py'  
    branches:
      - main
  pull_request:
    paths:
      - '**/*.py' 
    branches:
      - main

jobs:
  bandit:
    name: Run Bandit Security Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/upload-artifact@v4


      # Step 2: Set up Python (latest version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'latest'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Bandit
      - name: Run Bandit
        run: |
          bandit -r . --exclude tests --format txt --output bandit-report.txt
          cat bandit-report.txt

      # Step 5: Upload report (optional, for viewing artifacts)
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.txt
